log_format main '$remote_addr - $remote_user [$time_local] $scheme $host "$request" '
                '$status $body_bytes_sent "$http_referer" '
                '"$http_user_agent" "$http_x_forwarded_for"';

log_format proxy_log '[$time_local] $remote_addr - $remote_user - $server_name to: $upstream_addr: '
                     '$request status $status $uri upstream_response_time $upstream_response_time '
                     'msec $msec request_time $request_time';

server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        access_log /var/log/nginx/access.log main;
    }

    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log /var/log/nginx/proxy.log proxy_log;
    }

    location /basic_status {
        stub_status;
        allow all;
    }
}
